# Generated by Django 4.1.5 on 2023-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter main group dish', max_length=200)),
                ('text_main', models.CharField(help_text='Enter name dish', max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
